name: Build Aviator APK Fast

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Add Android Platform
        run: |
          cd template_src
          cordova platform rm android || true
          cordova platform add android

      - name: Build APK
        run: |
          cd template_src
          cordova build android --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aviator-Unsigned-APK
          path: template_src/platforms/android/app/build/outputs/apk/release/*.apk
