name: Build Aviator APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Cordova
        run: npm install -g cordova

      - name: Decode keystore (optional)
        run: |
          if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > template_src/keystore/my-release-key.keystore
          fi

      - name: Add Android platform
        run: |
          cd template_src
          cordova platform remove android || true
          cordova platform add android

      - name: Build APK
        run: |
          cd template_src
          if [ -f "keystore/my-release-key.keystore" ]; then
            cordova build android --release -- --keystore=template_src/keystore/my-release-key.keystore --storePassword=${{ secrets.KEYSTORE_PASSWORD }} --alias=${{ secrets.KEY_ALIAS }} --password=${{ secrets.KEY_ALIAS_PASSWORD }}
          else
            cordova build android --release
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: aviator-apk
          path: template_src/platforms/android/app/build/outputs/apk/release/*.apk
