name: Build and Sign Aviator APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-17-temurin
      ANDROID_HOME: ${{ runner.temp }}/android-sdk

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Cordova and Android tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget tar lib32stdc++6 lib32z1
          npm install -g cordova
          mkdir -p $ANDROID_HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv $ANDROID_HOME/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33"

      - name: Prepare Android platform
        run: |
          cd template_src
          cordova platform rm android || true
          cordova platform add android

      - name: Decode Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > template_src/keystore/my-release-key.keystore

      - name: Build APK
        run: |
          cd template_src
          cordova build android --release

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore template_src/keystore/my-release-key.keystore \
          -storepass $KEYSTORE_PASSWORD \
          -keypass $KEY_ALIAS_PASSWORD \
          template_src/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
          $KEY_ALIAS

      - name: Align APK
        run: |
          sudo apt-get install -y zipalign
          zipalign -v 4 template_src/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
          template_src/platforms/android/app/build/outputs/apk/release/Aviator-Pro.apk

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: Aviator-Pro-APK
          path: template_src/platforms/android/app/build/outputs/apk/release/Aviator-Pro.apk
