name: Build Aviator APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      # Install tar if missing
      - name: Install tar
        run: sudo apt-get update && sudo apt-get install -y tar unzip openjdk-17-jdk

      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install Cordova globally
      - name: Install Cordova
        run: npm install -g cordova

      # Decode keystore from base64 secret
      - name: Setup Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > template_src/keystore/my-release-key.keystore

      # Add Android platform
      - name: Add Android Platform
        run: |
          cd template_src
          cordova platform add android

      # Build APK
      - name: Build Release APK
        run: |
          cd template_src
          cordova build android --release

      # Sign APK using keystore secrets
      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore template_src/keystore/my-release-key.keystore \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_ALIAS_PASSWORD }} \
          template_src/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
          ${{ secrets.KEY_ALIAS }}

      # Align APK
      - name: Align APK
        run: |
          sudo apt-get install -y zipalign
          zipalign -v 4 \
          template_src/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
          template_src/platforms/android/app/build/outputs/apk/release/aviator.apk

      # Upload signed APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aviator-apk
          path: template_src/platforms/android/app/build/outputs/apk/release/aviator.apk
